debug=true

spring.application.name=${SPRING_APPLICATION_NAME:Logistics backend}
server.port=${SERVER_PORT:8082}
spring.config.activate.on-profile=local

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DATABASE:logistics_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

endpoints.frontend.url=${ENDPOINTS_FRONTEND_URL:http://localhost:3000}